### ISSUE TITLE
Port the Usage instructions

### ISSUE THREAD

**Issue by stevecox** [quicksprout/naas-api-client-python#24]
Please port the Ruby usage instructions to Python: https://github.com/quicksprout/naas-api-client-ruby/blob/master/USAGE.md

**Comment by nateklaiber** [comment]
[In Progress](https://github.com/quicksprout/naas-api-client-python/commit/fb60994b58a92d2b1c4e62003f6ca91fcfef84d3).

**Comment by nateklaiber** [comment]
@stevecox - The usage instructions were ported. I'll add other documentation for the new models.
